import os
import sys
import subprocess

def install_if_missing(package):
    try:
        __import__(package)
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", package])

install_if_missing("pip")

packages = [
    "requests"
    "time"
    "hashlib"
    "hmac"
    "asyncio"
    "python-telegram-bot"
]

import requests
import time
import hashlib
import hmac
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import (
    Application,
    CommandHandler,
    CallbackContext,
    MessageHandler,
    filters,
    CallbackQueryHandler,
)
import asyncio

API_KEY = 'mx0vglX75gG0MdTDB3'
SECRET_KEY = 'abebe1640bc14bf2b9b278b31225c13f'
MEXC_API_URL = "https://api.mexc.com/api/v3"
DEX_API_URL = "https://api.dexscreener.com"

ADMIN_ID = 5244655536
show_massage = True
is_checking_active = True

# قائمة الأزواج المطلوبة (يمكنك إضافتها يدويًا)
TARGET_PAIRS = ['BROCKUSDT', 'BNTUSDT', 'NTXUSDT', 'DEVVEUSDT', 'XOXNOUSDT', 'HTRUSDT', 'GQBUSDT', 'VOXELUSDT', 'LVNUSDT', 'LOKAUSDT', 'DEFIUSDT', 'SSEUSDT', 'F3USDT', 'CATTONUSDT', 'MANEKIUSDT', 'ARUSDT', 'BFICUSDT', 'SNTUSDT', 'BAKEUSDT', 'SWASHUSDT', 'IXSUSDT', 'ROAMUSDT', 'EVERUSDT', 'RINGAIUSDT', 'HANDYUSDT', 'OZONEUSDT', 'TUAUSDT', 'MYTHUSDT', 'MAIVUSDT', 'OOKIUSDT', 'DFUSDT', 'BOSONUSDT', 'SKAIUSDT', 'DOLZUSDT', 'UBXUSDT', 'VALORUSDT', 'NFTUSDT', 'GPTVUSDT', 'ALEOUSDT', 'CATSUSDT', 'FATUSDT', 'SCCUSDT', 'BERRYUSDT', 'INSPUSDT', 'GHTUSDT', 'ATRSUSDT', 'IQUSDT', 'LYUMUSDT', 'GRIFFAINUSDT', 'NTRNUSDT', 'SEEDUSDT', 'MORRAUSDT', 'MUBARAKAHUSDT', 'RSRUSDT', 'NSUSDT', 'IRISUSDT', 'XPLAUSDT', 'IDEAUSDT', 'T3AIUSDT', 'AXOLUSDT', 'GLINTUSDT', 'BIOUSDT', 'EMRLDUSDT', 'NACUSDT', 'AIDOGEUSDT', 'SOLUSDT', 'AAUSDT', 'NAPUSDT', 'QLINDOUSDT', 'KDAUSDT', 'XENUSDT', 'PNICUSDT', 'DOVUUSDT', 'INJUSDT', 'ELANDUSDT', 'GELUSDT', 'JUSTICEUSDT', 'FIOUSDT', 'HIFIUSDT', 'BSTCUSDT', 'ROCKUSDT', 'MELANIAUSDT', 'EURUSDT', 'ATNTUSDT', 'REFUSDT', 'DOBOUSDT', 'OBORTECHUSDT', 'ONDOUSDT', 'DKAUSDT', 'BVTUSDT', 'KANGUSDT', 'SABAIUSDT', 'KPNUSDT', 'STOOSUSDT', 'GOATUSDT', 'BONDUSDT', 'OVERUSDT', 'OKMUSDT', 'SYLOUSDT', 'SHIBSOLUSDT', 'VSYSUSDT', 'TFIUSDT', 'MUSDT', 'DOGWIFHATUSDT', 'CATIUSDT', 'SPHRUSDT', 'TBCUSDT', 'ATRUSDT', 'VELOUSDT', 'MRMINTUSDT', 'GARIUSDT', 'LPTUSDT', 'MONGUSDT', 'KIKIUSDT', 'AMUSDT', 'RXUSDT', 'ORAIUSDT', 'SYNTHUSDT', 'RIZOUSDT', 'SBR1USDT', 'ZKJUSDT', 'AIMMTUSDT', 'VNTRUSDT', 'HAROLDUSDT', 'FLYUSDT', 'LTTUSDT', 'CONVUSDT', 'BCBUSDT', 'AIBERAUSDT', 'ICNXUSDT', 'WELLUSDT', 'JUPUSDT', 'SOEXUSDT', 'EPXUSDT', 'MERLUSDT', 'TROLLSOLUSDT', 'AIDEEPGAMESUSDT', 'TREMPUSDT', 'PYTHIAUSDT', 'ZYPTOUSDT', 'PKRUSDT', 'GRIFTUSDT', 'TROLLUSDT', 'AIRIUSDT', 'GTCAIUSDT', 'SYSUSDT', 'MDOGSUSDT', 'TEVAUSDT', 'LEEUSDT', 'DOVAUSDT', 'AVAXUSDT', 'KITEAIUSDT', 'TJRMUSDT', 'XWGTUSDT', 'CELRUSDT', 'AIGPTUSDT', 'ANDYCOINBSCUSDT', 'SUIUSDT', 'PTCUSDT', 'NEXOUSDT', 'LOTTUSDT', 'NYAUSDT', 'PUSSUSDT', 'WEB3USDT', 'PHYUSDT', 'FDUSDUSDT', 'EAIUSDT', 'BLOCXUSDT', 'TAOUSDT', 'OMGUSDT', 'ERGUSDT', 'CDAUSDT', 'PHNIXUSDT', 'AINUUSDT', 'NEIUSDT', 'HTMUSDT', 'MUNITYUSDT', 'SNSYUSDT', 'MAVUSDT', 'PNDRUSDT', 'GTONUSDT', 'ATATUSDT', 'ARIXUSDT', 'EPICUSDT', 'STREAMUSDT', 'SEXYUSDT', 'HEMULEUSDT', 'BERAUSDT', 'HIPPOPUSDT', 'SEIUSDT', 'POWERAIUSDT', 'BAIUSDT', 'TRIOUSDT', 'COMUSDT', 'NEXAUSDT', 'GINNANUSDT', 'GAINSUSDT', 'ZEBUUSDT', 'BITBULLUSDT', 'WBTCUSDT', 'AURAUSDT', 'HIPPOSWAPUSDT', 'BVMUSDT', 'ZAXUSDT', 'LESTERUSDT', 'BXXUSDT', 'HEIUSDT', 'NZEROUSDT', 'MANAUSDT', 'COCKUSDT', 'PSPUSDT', 'CHRPUSDT', 'TAONUUSDT', 'COREUMUSDT', 'JAILSTOOLUSDT', 'OOEUSDT', 'ALGOUSDT', 'BLYUSDT', 'TUXCUSDT', 'GSWIFTUSDT', 'STRMUSDT', 'NRSUSDT', 'LAYERUSDT', 'AKITAXUSDT', 'ONTUSDT', 'SWELLUSDT', 'CROUSDT', 'SGPTUSDT', 'WINGUSDT', 'BLZUSDT', 'KATUSDT', 'RVNUSDT', 'KALISUSDT', 'LAIKAL2USDT', 'CWOLFUSDT', 'PIGCOINUSDT', 'TRXUSDT', 'ELGUSDT', 'DOMINUSDT', 'VIDTUSDT', 'SNAPUSDT', 'AIPUMPUSDT', 'BNAUSDT', 'CHONKYUSDT', 'THLUSDT', 'CHZUSDT', 'VAIUSDT', 'REXUSDT', 'DHNUSDT', 'LITHUSDT', 'SHILLUSDT', 'BABYBTCUSDT', 'MAGICUSDT', 'ZOOUSDT', 'OLUSDT', 'NODLUSDT', 'DBRUSDT', 'AUTOUSDT', 'VICEUSDT', 'MOGULUSDT', 'BDCUSDT', 'DOGGOSOLUSDT', 'BICITYUSDT', 'NULSUSDT', 'FANCUSDT', 'DEFXUSDT', 'PROSUSDT', 'MLNUSDT', 'SINUSDT', 'VRAUSDT', 'PSUSDT', 'CATCOINUSDT', 'WNTUSDT', 'W3SUSDT', 'GOLDUSDT', 'HAIUSDT', 'NIMBUSUSDT', 'DCOINUSDT', 'MAXSOLUSDT', 'CHRUSDT', 'TRAVAUSDT', 'SUSDT', 'TABOOUSDT', 'VR1USDT', 'SHELLUSDT', 'COOKIEUSDT', 'LBUSDT', 'MARSUSDT', 'SERUSDT', 'SDEXUSDT', 'ISPUSDT', 'FACTUSDT', 'STOGUSDT', 'PONKEUSDT', 'PEAQUSDT', 'BNCUSDT', 'MILLIUSDT', 'ROCKIUSDT', 'WNCGUSDT', 'CSIXUSDT', 'NGCUSDT', 'DEPCUSDT', 'KATAUSDT', 'LIBRAUSDT', 'ENFUSDT', 'FAVEUSDT', 'GUMMYUSDT', 'SANTOSUSDT', 'CAWUSDT', 'AEGISUSDT', 'OSOLUSDT', 'XECUSDT', 'HEUUSDT', 'FORMUSDT', 'BERTUSDT', 'DCBUSDT', 'LIONUSDT', 'BNBXBTUSDT', 'DEFROGSUSDT', 'RIVALUSDT', 'PRQUSDT', 'SLPUSDT', 'SBXUSDT', 'ETHWUSDT', 'LKIUSDT', 'SATUSDT', 'YAYUSDT', 'AVGUSDT', 'DOGEUSDT', 'SQGROWUSDT', 'KLVUSDT', 'IUSUSDT', 'ZTXUSDT', 'KP3RUSDT', 'FTONUSDT', 'TOKKIUSDT', 'ESEUSDT', 'TLMUSDT', 'RETUSDT', 'WVTRSUSDT', 'FITFIUSDT', 'TRU1USDT', 'POOLXUSDT', 'KEKEUSDT', 'DYPUSDT', 'NRKUSDT', 'MYSTUSDT', 'KAIUSDT', 'REMUSDT', 'ADNUSDT', 'GROKAIUSDT', 'ARPAUSDT', 'PEPAUSDT', 'RPLUSDT', 'DIKOUSDT', 'AESUSDT', 'JYAIUSDT', 'STRKUSDT', 'RAIUSDT', 'BLOKUSDT', 'ASTRUSDT', 'A8USDT', 'GOMININGUSDT', 'XRPUSDT', 'ASTOUSDT', 'ZEEUSDT', 'CRAIUSDT', 'LF1USDT', 'COCOROUSDT', 'FNFUSDT', 'IDEXUSDT', 'DOGINMEUSDT', 'MICROUSDT', 'MULTIUSDT', 'HOLDSTATIONUSDT', 'LUNCUSDT', 'KHEOWZOOUSDT', 'FLMUSDT', 'CPKUSDT', 'ALEPHUSDT', 'HOSKYUSDT', 'EMRUSDT', 'RXDUSDT', 'CLANKERUSDT', 'ATLASUSDT', 'GBCKUSDT', 'SANDUSDT', 'SQTUSDT', 'AIFUNUSDT', 'XPRUSDT', 'PSGUSDT', 'MFERUSDT', 'KINICUSDT', 'SUSHIUSDT', 'LUNAIUSDT', 'CVNUSDT', 'CAPTAINBNBUSDT', 'SXPUSDT', 'AGIIUSDT', 'AIPAYUSDT', 'MOODENGETHUSDT', 'ELIZAUSDT', 'HMSTRUSDT', 'INFRAUSDT', 'CAUUSDT', 'EWAUSDT', 'KARATEUSDT', 'VRLUSDT', 'AVAXAIUSDT', 'GVLUSDT', 'LAIUSDT', 'SPAUSDT', 'HNSUSDT', 'IDUSDT', 'ONONUSDT', 'AERGOUSDT', 'AISTUSDT', 'BTMUSDT', 'LOEUSDT', 'DOMIUSDT', 'ARRRUSDT', 'KRYUSDT', 'OGUSDT', 'GNSUSDT', 'XIONUSDT', 'ZENUSDT', 'ZPAYUSDT', 'HELIUSDT', 'VEXTUSDT', 'DVAUSDT', 'POWERUSDT', 'PUNCHUSDT', 'FINEETHUSDT', 'VPPUSDT', 'AMBUSDT', 'OLAUSDT', 'GRASSUSDT', 'DERIUSDT', 'GEODUSDT', 'NCDTUSDT', 'ELYSUSDT', 'APHBTUSDT', 'GTAUSDT', 'PCXUSDT', 'MRSUSDT', 'BUBBLEUSDT', 'ARTYUSDT', 'ALPHAUSDT', 'ZETAUSDT', 'AIAUSDT', 'POOHUSDT', 'SCBUSDT', 'DARKUSDT', 'BTFUSDT', 'OCBUSDT', 'CHEXUSDT', 'SHIROUSDT', 'TRUMPCOINUSDT', 'ARBGPTUSDT', 'SAFE4USDT', 'SKLUSDT', 'BOBOUSDT', 'GSTUSDT', 'XCADUSDT', 'LUMUSDT', 'JD98USDT', 'BROWNIEUSDT', 'ANIMEUSDT', 'CHESSUSDT', 'SWANUSDT', 'SKXUSDT', 'LQRUSDT', 'HIPPOUSDT', 'PEPUUSDT', 'VCFUSDT', 'PENUSDT', 'JTOUSDT', '1DOLLARUSDT', 'ATNUSDT', 'CEREUSDT', 'BANKUSDT', 'MORPHOUSDT', 'MBDUSDT', 'SUP1USDT', 'VTNUSDT', 'EVMOSUSDT', 'AXOUSDT', 'NEUTONUSDT', 'ELONUSDT', 'IRONUSDT', 'DUKOUSDT', 'G7USDT', 'BSCSUSDT', 'NAVIUSDT', 'JAMUSDT', 'LKYUSDT', 'BUNNYUSDT', 'EVDCUSDT', 'DOGAUSDT', 'OMUSDT', 'DOGEAIUSDT', 'HONEYUSDT', 'BONEUSDT', 'ALPINEUSDT', 'NAFIUSDT', 'NPCSUSDT', 'FULAUSDT', 'RUNEUSDT', 'PACOINUSDT', 'BADAIUSDT', 'SUIDEPINUSDT', 'EPIKUSDT', 'GAMEVIRTUALUSDT', 'RDTUSDT', 'AIPADUSDT', 'SVLUSDT', 'EXPERTUSDT', 'BABYBONKUSDT', 'SPELLUSDT', 'NKNUSDT', 'GENEUSDT', 'FDMUSDT', 'WEFIUSDT', 'SUPERANONUSDT', 'HPOUSDT', 'XCNUSDT', 'COPIUSDT', 'PINGOUSDT', 'DSYNCUSDT', 'LISTAUSDT', 'WALVUSDT', 'MYSTERYUSDT', 'BZZUSDT', 'NIRVANAUSDT', 'DMTUSDT', 'AMPUSDT', 'REBDUSDT', 'ANONUSDT', 'TMAIUSDT', 'WATERSOLUSDT', 'POLISUSDT', 'EDENUSDT', 'ZRXUSDT', 'ORDIUSDT', 'ZAIUSDT', 'AVLUSDT', 'DOLOUSDT', 'GTCOINUSDT', 'ALPHUSDT', 'FBUSDT', 'NOTUSDT', 'BBTUSDT', 'BROCCOLIF3BUSDT', 'FUSEUSDT', 'BARSUSDT', 'STBUUSDT', 'ARBUSDT', 'BASEDPEPEUSDT', 'GIGAUSDT', 'TRACEUSDT', 'BCUSDT', 'SVTSUSDT', 'MINIMAUSDT', 'NRGUSDT', 'GFALUSDT', 'ASMATCHUSDT', 'CLVUSDT', 'EURIUSDT', 'MIGGLESUSDT', 'SNIFTUSDT', 'BITBOARDUSDT', 'READYUSDT', 'EFFECTUSDT', 'GMXUSDT', 'IOSTUSDT', 'WXUSDT', 'RENQUSDT', 'RADUSDT', 'BTCFIUSDT', 'MINEBTCUSDT', 'LADYSUSDT', 'O4DXUSDT', 'KERNELUSDT', 'BDTCUSDT', 'WUFUSDT', 'BABYSORAUSDT', 'VEMPUSDT', 'BGSCUSDT', 'HUAHUAUSDT', 'ARCUSDT', 'SEAMUSDT', 'NEOTECHUSDT', 'BANANAS31USDT', 'UPTUSDT', 'OMOMUSDT', 'GAME2USDT', 'CARRUSDT', 'LAUNCHUSDT', 'AIAGENTUSDT', 'BADUSDT', 'SORAUSDT', 'SMLUSDT', 'AVAAIUSDT', 'SENUSDT', 'BILLYUSDT', 'NWSUSDT', 'SPLASHUSDT', 'EDLCUSDT', 'NFCUSDT', 'EVADOREUSDT', 'FLRUSDT', 'OGGYBSCUSDT', 'TOMUSDT', 'CLEARUSDT', 'CATCHUSDT', 'BATUSDT', 'CHPDUSDT', 'ELIXUSDT', 'NETVRUSDT', 'SWGTUSDT', 'MKRUSDT', 'SOLVUSDT', 'N2TUSDT', 'AMOUSDT', 'ENSUSDT', 'SDLUSDT', 'CBPAYUSDT', 'LNDXUSDT', 'PYRUSDT', 'TURBOUSDT', 'TOMIUSDT', 'SNEKUSDT', 'ALPACAUSDT', 'ACQUSDT', 'SBRUSDT', 'FRCUSDT', 'LUIGIUSDT', 'GURUUSDT', 'BMTUSDT', 'HNBUSDT', 'EVERYAIUSDT', 'QRLUSDT', 'EFCUSDT', 'PAWZONEUSDT', 'BCUTUSDT', 'BSTUSDT', 'OFTUSDT', 'INTERUSDT', 'KULAUSDT', 'TSUKAUSDT', 'SPONSTARUSDT', 'RBNTUSDT', 'BDPUSDT', 'GMEEUSDT', 'KEYCATUSDT', 'SOULSUSDT', 'GMUSDT', 'WITCHUSDT', 'ATOMUSDT', 'COCAUSDT', 'WFTUSDT', 'BLENDRUSDT', 'BXNUSDT', 'TONUSDT', 'SWXUSDT', 'TRCUSDT', 'BETAUSDT', 'KOKUUSDT', 'CHIPUSDT', 'CBKUSDT', 'FUUSDT', 'ZCXUSDT', 'REEFUSDT', 'GOGLZUSDT', 'GBUSDT', 'GTHEDOGUSDT', 'MOODENGUSDT', 'PLOPUSDT', 'ETCUSDT', 'SOHUSDT', 'DEPUSDT', 'BOBUSDT', 'LTDUSDT', 'WEMIXUSDT', 'FARTOKENUSDT', 'SCFUSDT', 'NWCUSDT', 'BTCBAMUSDT', 'PEPE2USDT', 'GONUSDT', 'WODUSDT', 'REVOUSDT', 'TAMAUSDT', 'BACUSDT', 'KIBUSDT', 'DBCUSDT', 'CWARUSDT', 'ILVUSDT', 'WLDUSDT', 'STOSUSDT', 'RCUSDT', 'BSAUSDT', 'WELSHUSDT', 'TRUFUSDT', 'TLFUSDT', 'XRP2USDT', 'FTTUSDT', 'AEVOUSDT', 'HYPERUSDT', 'SLINGUSDT', 'KIBSHIUSDT', 'CHEWYUSDT', 'NEIROUSDT', 'XLMUSDT', 'CATUSDT', 'OLASUSDT', 'MBPUSDT', 'MOBYUSDT', 'ORCAUSDT', 'ZUZALUUSDT', 'BOBBSCUSDT', 'USDMUSDT', 'GROKUSDT', 'MCNUSDT', 'KRLUSDT', 'LMCSWAPUSDT', 'TTMUSDT', 'SPACEPIUSDT', 'KANGOUSDT', 'CAPUSDT', 'OCHUSDT', 'UXLINKUSDT', 'AAVEUSDT', 'FTUSDT', 'REDXUSDT', 'ABELUSDT', 'CREPEUSDT', '1CATUSDT', 'CHEEMSUSDT', 'HAHAUSDT', 'PAWUSDT', 'FXSUSDT', 'OPUSDT', 'HZNUSDT', 'POLSUSDT', 'BBBUSDT', 'PIVNUSDT', 'HOMUSDT', 'SLERFUSDT', 'WATERUSDT', 'HEARTUSDT', 'TAPUSDT', 'SRDSUSDT', 'MLTUSDT', 'SOLOUSDT', 'VERTUSDT', 'DOGEGOVUSDT', 'ZNDUSDT', 'CTCUSDT', 'PUNDIAIUSDT', 'ALICEUSDT', 'CVXUSDT', 'FARTCOINUSDT', 'PIDOGUSDT', 'PLANETUSDT', 'BARUSDT', 'HONKUSDT', 'ZKPUSDT', 'ALPHAOFSOLUSDT', 'PKTCUSDT', 'HARRYUSDT', 'TRVLUSDT', 'AUKIUSDT', 'TRACUSDT', 'CAKEUSDT', 'ASSISTUSDT', 'SAGAUSDT', 'USUALUSDT', 'LAZIOUSDT', 'BTYUSDT', 'BITCATUSDT', 'NEARUSDT', 'ADUSDT', 'ABIUSDT', 'GRTUSDT', 'SAUCEUSDT', 'LNQUSDT', 'LITHOUSDT', 'CHOUSDT', 'AIATUSDT', 'RBTUSDT', 'KRESTUSDT', 'TONUPUSDT', 'ANON1USDT', 'PEMUSDT', 'AMCUSDT', 'RWAUSDT', 'VVAIFUUSDT', 'ELONMARSUSDT', 'WXTUSDT', 'PAIDUSDT', 'AVCUSDT', 'EGGUSDT', 'NCUSDT', 'VINEUSDT', 'LYPUSDT', 'ABXUSDT', 'CELLAUSDT', 'DOPUSDT', 'OSMOUSDT', 'KLSUSDT', 'BRISEUSDT', 'HPEPEUSDT', 'SHITCUSDT', 'RETARDIOUSDT', 'FTRUSDT', 'AZITUSDT', 'YPREDUSDT', 'HOPRUSDT', 'BUCKAZOIDSUSDT', 'SGEUSDT', 'KAIAUSDT', 'NOTAIUSDT', 'RONUSDT', 'NILUSDT', 'DYNAUSDT', 'SQUADUSDT', 'YIDOUSDT', 'ORDUSDT', 'BEAMUSDT', 'ELKUSDT', 'NFPUSDT', 'KAVAUSDT', 'CRGPTUSDT', 'MASUSDT', 'CARUSDT', 'JUCUSDT', 'AVENTISAIUSDT', 'STARUSDT', 'UMAUSDT', 'MONKYUSDT', 'TRKXUSDT', 'PORT3USDT', 'CENNZUSDT', 'REIUSDT', 'QTUMUSDT', 'DDUSDT', 'XELSUSDT', 'MEMEFIUSDT', 'BABYBNBUSDT', 'BERAFIUSDT', 'BIGTIMEUSDT', 'AITECHUSDT', 'QAIUSDT', '1INCHUSDT', 'LLUSDT', 'MXNAUSDT', 'WAVESUSDT', 'DYMUSDT', 'AIMONICAUSDT', 'AIOTUSDT', 'BCTUSDT', 'SHXUSDT', 'MEIUSDT', 'DOGELONUSDT', 'AURUSDT', 'ANYONEUSDT', 'ALCHUSDT', 'MRSOONUSDT', 'LEVERUSDT', 'AGROUSDT', 'GOATSUSDT', 'NAOUSDT', 'SHRUBUSDT', 'MEDXUSDT', 'GAIAUSDT', 'MLCUSDT', 'SHONGUSDT', 'ATHUSDT', 'JTFUSDT', 'XRUSDT', 'LEOXUSDT', 'FWOGUSDT', 'MFTUSDT', 'XCHNGUSDT', 'CBYUSDT', 'RGUSDT', 'TRTUSDT', 'CAIRUSDT', 'STEEMUSDT', 'NLSUSDT', 'XVGUSDT', 'ALTUSDT', 'APEDUSDT', 'LOLUSDT', 'ZORAUSDT', 'ZBCNUSDT', 'REZUSDT', 'LCGUSDT', 'ZEXUSDT', 'GECUSDT', 'USDCUSDT', '5IREUSDT', 'KRIPTOUSDT', 'ANALOSUSDT', 'ARTFIUSDT', 'BITFOLIOUSDT', 'VARCHUSDT', 'CHAXUSDT', 'CTDUSDT', 'WAVUSDT', 'GEARUSDT', 'JUNOUSDT', 'DUELUSDT', 'ICPXUSDT', 'FYDEUSDT', 'APEPEUSDT', 'C4EUSDT', 'LEARNUSDT', 'CREOUSDT', 'OBTUSDT', 'OXUSDT', 'THREEUSDT', 'LOBOUSDT', 'PROMUSDT', 'NCTRUSDT', 'WEPEUSDT', 'SERAPHUSDT', 'DKSUSDT', 'DOGUSDT', 'NUMUSDT', 'PLNUSDT', 'SUNWUKONGUSDT', 'SONICUSDT', 'MOZUSDT', 'PNUTUSDT', 'FLAIUSDT', 'OMNIAUSDT', 'DAOUSDT', 'SETAIUSDT', 'RLYUSDT', 'FIDAUSDT', 'LIKEUSDT', 'STOUSDT', 'XCHUSDT', 'ROUTEUSDT', 'XNAUSDT', 'SDNUSDT', 'MONIEUSDT', 'VICUSDT', 'VSCUSDT', 'XAUTUSDT', 'EXSUSDT', 'SPOLUSDT', 'QNTUSDT', 'COWUSDT', 'CITYUSDT', 'FPEPEUSDT', 'UFTUSDT', 'EYWAUSDT', 'AFCUSDT', 'KPCUSDT', 'HMNDUSDT', 'NEOSUSDT', 'ATSUSDT', 'DAGUSDT', 'MIRUSDT', 'TSTUSDT', 'BROCCOLIUSDT', 'NMTUSDT', 'GAMESTOPUSDT', 'OBICOINUSDT', 'REDUSDT', 'BCCOINUSDT', 'SDUSDT', 'JSETUSDT', 'UNIT0USDT', 'KAMAUSDT', 'MOCHIUSDT', 'PENDLEUSDT', 'BITCIUSDT', 'LIF3USDT', 'LBMUSDT', 'MANUSDT', 'CELUSDT', 'LQTYUSDT', 'SAUBERUSDT', 'FARMUSDT', 'SKICATUSDT', 'SPKYUSDT', 'AINUSDT', 'ZANOUSDT', 'SNFTUSDT', 'CRETAUSDT', 'HARAMBEAIUSDT', 'GASPUSDT', 'ICENETWORKUSDT', 'ICTUSDT', 'FLUIDUSDT', 'GTCUSDT', 'MBLUSDT', 'KLIMAUSDT', 'SMARTAIUSDT', 'PROPSUSDT', 'NATIXUSDT', 'SCPTUSDT', 'PONCHUSDT', 'WCTUSDT', 'OGYUSDT', 'METAVUSDT', 'GLUTEUUSDT', 'BLENDUSDT', 'EMLUSDT', 'NFTCUSDT', 'PELFUSDT', 'DIONEUSDT', 'PEARUSDT', 'WIFUSDT', 'PMTUSDT', 'DADDYUSDT', 'HLOUSDT', 'TENETUSDT', 'BOBAUSDT', 'AEROBUDUSDT', 'MCBUSDT', 'SUPRAUSDT', 'FAKEAIUSDT', 'WOLFUSDT', 'XRDUSDT', 'SVNUSDT', 'SFPUSDT', 'FUELUSDT', 'SATOUSDT', 'VOIUSDT', 'RYOUSDT', 'WATUSDT', 'MNRYUSDT', 'HASHAIUSDT', 'SHIBASHOOTUSDT', 'NIGHTUSDT', 'ELONSOLUSDT', 'NIGELLAUSDT', 'LOOKSUSDT', 'FUSDT', 'MAJORUSDT', 'VESUSDT', 'SUIAIUSDT', 'BABYAUSDT', 'LOCKUSDT', 'LLDUSDT', 'SCUSDT', 'AIGOUSDT', 'COMAIUSDT', 'VINUUSDT', 'SUKUUSDT', 'THGUSDT', 'IXTUSDT', 'SAIUSDT', 'SIGNUSDT', 'ZBUUSDT', 'MANTAUSDT', 'ZLWUSDT', 'VOWUSDT', 'BOOEUSDT', 'FOXUSDT', 'CPUSDT', 'YOLOUSDT', 'NEROXUSDT', 'SIDUSUSDT', 'OMNICATUSDT', 'CHATUSDT', 'RUNECOINUSDT', 'TINUSDT', 'ROSEUSDT', 'BURGERUSDT', 'SFINUSDT', 'WSDMUSDT', 'DIAMUSDT', 'JOEUSDT', 'MEMHASHUSDT', 'SUNDOGUSDT', 'NVIRUSDT', 'CSIGMAUSDT', 'CLUBUSDT', 'TAIKOUSDT', 'VOIDUSDT', 'BLUE1USDT', 'MOONEDUSDT', 'STFXUSDT', 'BKNUSDT', 'OOBITUSDT', 'MADUSDT', 'OSAKUSDT', 'AIDOGEXLMUSDT', 'RECORDUSDT', 'RIBBITUSDT', 'EPTUSDT', 'PAIUSDT', 'RSS3USDT', 'OXOAUSDT', 'BGBUSDT', 'ABBCUSDT', 'INSNUSDT', 'GINOAUSDT', 'OGNUSDT', 'WSMUSDT', 'LINGOUSDT', 'EKTAUSDT', 'CHIRPUSDT', '5SCAPEUSDT', 'RIBUSDT', 'ZIGUSDT', 'HMTUSDT', 'GUNUSDT', 'VTHOUSDT', 'VCUSDT', 'CAUSDT', 'STRAWBERRYAIUSDT', 'HYCOUSDT', 'LFUSDT', 'DNXUSDT', 'SDMUSDT', 'SUNCATUSDT', 'ATTUSDT', 'JSTUSDT', 'LBRUSDT', 'FMCUSDT', 'HARRYBOLZUSDT', 'AILUSDT', 'OBIUSDT', 'VOLTUSDT', 'AGCUSDT', 'VANRYUSDT', 'SHIBAUSDT', 'GPTPLUSUSDT', 'QKCUSDT', 'OVRUSDT', 'SOLVEXUSDT', 'LYXUSDT', 'MEMDEXUSDT', 'FULLSENDUSDT', 'NEXDUSDT', 'LBTCUSDT', 'MAXUSDT', 'VERSEUSDT', 'GMEUSDT', 'TKXUSDT', 'PLTUSDT', 'GRAMUSDT', 'ELFUSDT', 'DEDAUSDT', 'LUMIAUSDT', 'MINARUSDT', 'APXUSDT', 'BVGUSDT', 'XTERUSDT', 'MEMESAIUSDT', 'DIGIUSDT', 'LDOUSDT', 'DINGOUSDT', 'ZEROUSDT', 'HYDRAUSDT', 'NAKAUSDT', 'WOOUSDT', 'TTCOINUSDT', 'FLOKIUSDT', 'STAGEUSDT', 'FARTBOYUSDT', 'MXUSDT', 'ANVLUSDT', 'RONALDUSDT', 'MPAAUSDT', 'NRNUSDT', 'HAPPYUSDT', 'DRIFTUSDT', 'LMTUSDT', 'AZCUSDT', 'BANANAUSDT', 'SOLARUSDT', 'ARSUSDT', 'TERMUSDT', 'CFXUSDT', 'STCUSDT', 'NOMOXUSDT', 'BUBBUSDT', 'LCATUSDT', 'SR30USDT', 'BTTUSDT', 'SCAUSDT', 'UNISUIUSDT', 'AP3XUSDT', 'JETTONUSDT', 'MBXUSDT', 'XYROUSDT', 'RNVIUSDT', 'CELOUSDT', 'TCTUSDT', 'UPOUSDT', 'PARTIUSDT', 'AIETUSDT', 'BRETTETHUSDT', 'SUNUSDT', 'STBOTUSDT', 'AXMUSDT', 'PIKAUSDT', 'TETUSDT', 'ZKLUSDT', 'XERSUSDT', 'XDCUSDT', 'RJVUSDT', 'RILLAUSDT', 'HSXUSDT', 'BOOUSDT', 'HYPEUSDT', 'IPUSDT', 'BUZZUSDT', 'BELLSUSDT', 'SOVRNUSDT', 'BENDOGUSDT', 'APPUSDT', 'KAPUSDT', 'SAFEUSDT', 'PLUMEUSDT', 'DASHUSDT', 'KOINUSDT', 'OZOUSDT', 'BABYELONUSDT', 'DEAIUSDT', 'SEROUSDT', 'KIMAUSDT', 'GEMSUSDT', 'TPYUSDT', 'INCNUSDT', 'VISIONUSDT', 'ORTUSDT', 'ULTIMAUSDT', 'OMNIUSDT', 'METALUSDT', 'RARIUSDT', 'PYTHUSDT', 'AOUSDT', 'NOSUSDT', 'DOGENUSDT', 'BANUSDT', 'BABYNEIROBNBUSDT', 'PALMAIUSDT', '2MOONUSDT', 'HBARUSDT', 'LOOMUSDT', 'UNMUSDT', 'ORDSUSDT', 'APNUSDT', 'GALAXISUSDT', 'SNPTUSDT', 'PIPPINUSDT', 'SIRENUSDT', 'AIAKITAUSDT', 'PPCUSDT', 'HOTKEYUSDT', 'KHAIUSDT', 'CHILLGUYUSDT', 'FUDUSDT', 'LEFEEFUSDT', 'AIX9USDT', 'ZKIDUSDT', 'TATSUUSDT', 'TLOSUSDT', 'RITEUSDT', 'PIXFIUSDT', 'SIXUSDT', 'AINTIUSDT', 'OPN1USDT', 'WALLETUSDT', 'GHIBLIUSDT', 'VISTAUSDT', 'RBCUSDT', 'NTMPIUSDT', 'GULLUSDT', 'RENTAUSDT', 'HYPCUSDT', 'MUBIUSDT', 'XMRUSDT', 'L3USDT', 'BALUSDT', 'MAPOUSDT', 'RAYUSDT', 'EGPUSDT', 'JOULEUSDT', 'GREENBTCUSDT', 'IMGNUSDT', 'SKRUSDT', 'ASSUSDT', 'SAFEMOONSOLUSDT', 'MUCUSDT', 'QIUSDT', 'MOEWUSDT', 'ELON4AFDUSDT', 'VRTXUSDT', 'EIGENUSDT', 'CBXUSDT', 'POGAIUSDT', 'PELLUSDT', 'CNSUSDT', 'TRUMP404USDT', 'VPTUSDT', 'ARCHUSDT', 'OSMIUSDT', 'CROWN2USDT', 'RVFUSDT', 'PXPUSDT', 'SWAPUSDT', 'SATSUSDT', 'PORTUMAUSDT', 'ISLANDUSDT', 'SCOTTYAIUSDT', 'FEARUSDT', 'NAVXUSDT', 'JFOXUSDT', 'PAWSUSDT', 'SERAUSDT', 'TETSUOUSDT', 'RLCUSDT', 'UQCUSDT', 'ABONDUSDT', 'BDXUSDT', 'PEPEUSDT', 'GSYSUSDT', 'FSNUSDT', 'CHILLAXUSDT', 'SEILORUSDT', 'HONORUSDT', 'ARKTUSDT', 'KRUUSDT', 'GPSUSDT', 'XETAUSDT', 'IOUSDT', 'NOVAUSDT', 'FLUXUSDT', 'CRVUSDT', 'BICOUSDT', 'UNOUSDT', 'ACSUSDT', 'APUSDT', 'W3GGUSDT', 'VEEUSDT', 'MOGUSDT', 'NUTSUSDT', 'MOBXUSDT', 'SUPRUSDT', 'SKOPUSDT', 'ABCUSDT', 'RKFIUSDT', 'PHILUSDT', 'FORTUSDT', 'EGOUSDT', 'SEDAUSDT', 'PAALUSDT', 'TRIASUSDT', 'ZELIXUSDT', 'LGCTUSDT', 'SMOGUSDT', 'SCRTUSDT', 'VICSUSDT', 'DCUSDT', 'PENGUSDT', 'XXUSDT', 'SALUSDT', 'MEGAHEROUSDT', 'APEUSDT', 'AUCUSDT', 'QTLXUSDT', 'LIFEUSDT', 'HYPERSKIDSUSDT', 'MARS1USDT', 'DOGECOINUSDT', 'DEXTFUSDT', 'VADERUSDT', 'JERRYUSDT', 'SAKAIUSDT', 'GROOVEUSDT', 'PAINUSDT', 'GMMUSDT', 'LVVAUSDT', 'ZENCOINUSDT', 'NYMUSDT', 'GRAILUSDT', 'CEEKUSDT', 'ARVUSDT', 'ZKUSDT', 'ZCDUSDT', 'STRIKEUSDT', 'ADAUSDT', 'STPTUSDT', 'TORSYUSDT', 'CANTOUSDT', 'B3USDT', 'ACXUSDT', 'RUNIUSDT', 'QORPOUSDT', 'HIVEUSDT', 'SWARMSUSDT', 'NEIROCTOUSDT', 'STXUSDT', 'ALEUSDT', 'JANUSDT', 'SMILEUSDT', 'MVLUSDT', 'STAR10USDT', 'MINXUSDT', 'IVFUNUSDT', 'VMINTUSDT', 'ACMUSDT', 'WEXOUSDT', 'ARCAUSDT', 'SSWPUSDT', 'EULUSDT', 'FNCTUSDT', 'CLAIUSDT', 'MOVEUSDT', 'DOGSUSDT', 'AEROUSDT', 'EOSUSDT', 'CONXUSDT', 'POLUSDT', 'GTAVIUSDT', 'DECHATUSDT', 'FUTUREUSDT', 'MLGUSDT', 'WHITEUSDT', 'DEXEUSDT', 'W3FUSDT', 'P3DUSDT', 'AICUSDT', 'TONNYUSDT', 'ALONUSDT', 'ALUSDT', 'METISUSDT', 'LINKUSDT', 'XSPECTARUSDT', 'KINEUSDT', 'MEWUSDT', 'CULTDAOUSDT', 'AIHUSDT', 'AVTMUSDT', 'BIT1USDT', 'PEPUSDT', 'BAXUSDT', 'KASTAUSDT', 'SCRUSDT', 'FOURUSDT', 'UTKUSDT', 'GMRTUSDT', 'ZUSDT', 'GRAFIUSDT', 'NPCUSDT', 'ADSUSDT', 'XPMUSDT', 'ZRCUSDT', 'SUPERAIUSDT', 'GSTOPUSDT', 'LEOUSDT', 'MARSHUSDT', 'AIBBUSDT', 'ISLMUSDT', 'PENDULUMUSDT', 'DEODUSDT', 'TOSHIUSDT', 'ETF500USDT', 'XINUSDT', 'PINUSDT', 'SWEATUSDT', 'POLYDOGEUSDT', 'AIWUSDT', 'RTFUSDT', 'PUMPUSDT', 'NAIUSDT', 'COLLEUSDT', 'AVAILUSDT', 'MINUSDT', 'TRUMPUSDT', 'KOYUSDT', 'UBXSUSDT', 'IOTXUSDT', 'FORWARDUSDT', 'FOMOUSDT', 'PUMPAIUSDT', 'TRADEUSDT', 'TUBESUSDT', 'ALIUSDT', 'TOKENUSDT', 'WHYUSDT', 'HFTUSDT', 'FLAYUSDT', 'DCRUSDT', 'GZONEUSDT', 'CHEFUSDT', 'OGGYETHUSDT', 'AOSUSDT', 'CYBERUSDT', 'STEPNUSDT', 'ALVAUSDT', 'NEXMUSDT', 'ORDERUSDT', 'UPCUSDT', 'SNRNUSDT', 'AITPROTOCOLUSDT', 'SECUUSDT', 'HENAIUSDT', 'WINRUSDT', 'GQUSDT', 'SPEEDUSDT', 'SOLAMAUSDT', 'MINAUSDT', 'UWONUSDT', 'CYBONKUSDT', 'DERPUSDT', 'OCTAUSDT', 'STORMUSDT', 'BXCUSDT', 'RBAXUSDT', 'WINXUSDT', 'JLPUSDT', 'DGCUSDT', 'SYNUSDT', 'RMVUSDT', 'POLCUSDT', 'MUMUUSDT', 'MASSUSDT', 'ULXUSDT', 'ALEXUSDT', 'IZIUSDT', 'CRTAIUSDT', 'BONGOUSDT', 'WORKUSDT', 'MONUSDT', 'TICOUSDT', 'SCIHUBUSDT', 'TELUSDT', 'N3USDT', 'L1USDT', 'GNONUSDT', 'CARVUSDT', 'GTAIUSDT', 'HXDUSDT', 'RPKUSDT', 'GFMUSDT', 'GPUSUSDT', 'ZENTUSDT', 'IVPAYUSDT', 'USTCUSDT', 'BASEDAIUSDT', 'ORFYUSDT', 'TKOUSDT', 'BSWUSDT', 'WALKUSDT', 'QBXUSDT', 'AIMXUSDT', 'ZYNUSDT', 'PIGUSDT', 'SGTUSDT', 'INVUSDT', 'FLIXUSDT', 'JUSDT', 'KENDUUSDT', 'MEOWCATUSDT', 'FUCOINUSDT', 'TLCUSDT', 'INTRUSDT', 'ICPUSDT', 'SIMPSONUSDT', 'GLQUSDT', 'FTNUSDT', 'EWTUSDT', 'NZCUSDT', 'SQDUSDT', 'PORTALUSDT', 'SVJUSDT', 'SMILEYUSDT', 'SDRUSDT', 'NCTUSDT', 'SRMUSDT', 'ALMUSDT', 'WNKUSDT', 'WENUSDT', 'CHEQUSDT', 'FIROUSDT', 'SCOTTYUSDT', 'PIUSDT', 'CDXUSDT', '4EVERUSDT', 'YGGUSDT', 'TRIVIAUSDT', 'MODALAIUSDT', 'ZILUSDT', 'SHIDOUSDT', 'OFNUSDT', 'DRAGON404USDT', 'MAVIAUSDT', 'YULIUSDT', 'MRSTUSDT', 'AGLDUSDT', 'FAIUSDT', 'CHANGEUSDT', 'UNPUSDT', 'SAVMUSDT', 'YZYSOLUSDT', 'MNEMOUSDT', 'APEXUSDT', 'GENOMEUSDT', 'SWINGBYUSDT', 'DRNUSDT', 'PMXUSDT', 'SMARTUSDT', 'ALUUSDT', 'GENOUSDT', 'MODEUSDT', 'VVVUSDT', 'SMARSUSDT', 'VELODROMEUSDT', 'PRXUSDT', 'GRANDUSDT', 'KMNOUSDT', 'MAUSDT', 'PPTUSDT', 'FNCYUSDT', 'DUSDT', 'BCHUSDT', 'YFIUSDT', 'FLOCKUSDT', 'FEGUSDT', 'WNXMUSDT', 'SOVUSDT', 'KERMITUSDT', 'DORAUSDT', 'TREATUSDT', 'SYRUPUSDT', 'EDOGUSDT', 'NIZAUSDT', 'SOVMUSDT', 'GINUXUSDT', 'JEMIUSDT', 'PEOPLEUSDT', 'A1XUSDT', 'BIOFIUSDT', 'SPSUSDT', 'PORUSDT', 'SGBUSDT', 'SCOTUSDT', 'BEAMXUSDT', 'XRPAYNETUSDT', 'STATUSDT', 'VGXUSDT', 'KOIIUSDT', 'DOTUSDT', 'XYMUSDT', 'SOSOUSDT', 'TESLAIUSDT', 'PIVXUSDT', 'SMURFCATUSDT', 'CROWNUSDT', 'NMDUSDT', 'DNAUSDT', 'ABEYUSDT', 'ENAUSDT', 'TUTUSDT', 'GANGUSDT', 'BRLNUSDT', 'UMBUSDT', 'HBDUSDT', 'SLNUSDT', 'KSMUSDT', 'OXYZUSDT', 'PTHUSDT', 'MASKUSDT', 'LAK3USDT', 'IMTUSDT', 'CTFUSDT', 'DRAUSDT', 'PEPE1USDT', 'RAREUSDT', 'TAOCATUSDT', 'HINTUSDT', 'SWFTCUSDT', 'KOMUSDT', 'ACHUSDT', 'LIFEMUSDT', 'MINTUSDT', 'XARUSDT', 'XBUSDT', 'SMOLEUSDT', 'ANTUSDT', 'CCDUSDT', 'NOWUSDT', 'QUBICUSDT', 'APTUSDT', 'GHUBUSDT', 'HOODUSDT', 'DODOUSDT', 'PORKUSDT', 'PLYRUSDT', 'LAVAUSDT', 'TFUELUSDT', 'FORTHUSDT', 'COREUSDT', 'LUCEUSDT', 'ELYUSDT', 'CETUSUSDT', 'ELXUSDT', 'ORNJUSDT', 'HELLOUSDT', 'XUSDT', 'SUIRWAUSDT', 'MNTUSDT', 'FYNUSDT', '2024PUMPUSDT', 'HABIBIUSDT', 'OLEUSDT', 'CWEBUSDT', 'SNAIUSDT', 'CGXUSDT', 'EVRUSDT', 'PNGUSDT', 'HDROUSDT', 'PAYUUSDT', 'BABYSHARKUSDT', 'NFEUSDT', 'BENJIUSDT', 'IMGNAIUSDT', 'JOYSTREAMUSDT', 'M87USDT', 'DCKUSDT', 'SOLSUSDT', 'ASSAIUSDT', 'XELUSDT', 'TCAPYUSDT', 'BRNUSDT', 'LETITUSDT', 'TRUMPIUSUSDT', 'BABYUSDT', 'AMEUSDT', 'NLINKUSDT', 'XTZUSDT', 'XPUSDT', 'BABYNEIROUSDT', 'MCCHEESEUSDT', 'DYDXUSDT', 'SUIPUSDT', 'ZIGAPUSDT', 'BLASTUSDT', 'GRPHUSDT', 'FISUSDT', 'MMDUSDT', 'BEERUSDT', 'EDUUSDT', 'BLURUSDT', 'BELUSDT', 'CATBOYUSDT', 'GODSUSDT', 'EMYCUSDT', 'FISHWUSDT', 'ONEUSDT', 'CBLUSDT', 'VERBUSDT', 'XSWAPUSDT', 'AZURUSDT', 'NIBIUSDT', 'PHBUSDT', 'WBCUSDT', 'MUSKITUSDT', 'TOPUSDT', 'G3USDT', 'NEONUSDT', 'LAIKAUSDT', 'HOTUSDT', 'AICOREUSDT', 'CPHUSDT', 'SAROSUSDT', 'BTC2USDT', 'THEUSDT', 'SPFCUSDT', 'PEIPEIUSDT', 'BNBAIUSDT', 'GHSTUSDT', 'CSTARSUSDT', 'LOFIUSDT', 'DROPUSDT', 'MG8USDT', 'REDOUSDT', 'DFCUSDT', 'SPARKLETUSDT', 'PBUXUSDT', 'BEANSUSDT', 'ROOTUSDT', 'KAITOUSDT', 'GUIUSDT', 'CSPRUSDT', 'CSWAPUSDT', 'AGRIUSDT', 'CULTUSDT', 'RPGUSDT', 'BOTIFYUSDT', 'UNFIUSDT', 'SECONDUSDT', 'WCOUSDT', 'SCCPUSDT', 'RNTUSDT', 'LATUSDT', 'STETHUSDT', 'BHOUSDT', 'ORBTUSDT', 'AIXBTUSDT', 'FANUSDT', 'ARGUSDT', 'LSDUSDT', 'RETIKUSDT', 'XLSUSDT', 'XVSUSDT', 'INSURUSDT', 'PIKABOSSUSDT', 'ELONDOGEUSDT', 'PHAUSDT', 'SMRUSDT', 'TRIBEUSDT', 'FREEDOMUSDT', 'QUICKUSDT', 'TGRASSUSDT', 'BUTTHOLEUSDT', 'MSMUSDT', 'AVAUSDT', 'VIVIUSDT', 'TWTUSDT', 'SFIUSDT', 'UUSDT', 'CYBROUSDT', 'VIAUSDT', 'FURYUSDT', 'GOCHUUSDT', 'RIXENUSDT', 'GLMRUSDT', 'KOMAUSDT', 'DINEROUSDT', 'EGAXUSDT', 'BNBUSDT', 'ZROUSDT', 'RIFUSDT', 'OIKUSDT', 'DOAIUSDT', 'ETNUSDT', 'CATEUSDT', 'DOLANUSDT', 'KUSDT', 'CHCUSDT', 'ULTIUSDT', 'MPCUSDT', 'MNSRYUSDT', 'C98USDT', 'BRUSDT', 'NHTUSDT', 'STNKUSDT', 'EKUUSDT', 'ROCOUSDT', 'WILDUSDT', 'TUSDT', 'YFIIUSDT', 'P888USDT', 'SUAIUSDT', 'HSKUSDT', 'HKTMUSDT', 'LYNXUSDT', 'DINUSDT', 'BDROPUSDT', 'SPTUSDT', 'BZRUSDT', 'CWAUSDT', 'MPLXUSDT', 'ANKRUSDT', 'CLYUSDT', 'SIGMAUSDT', 'MEMEUSDT', 'LANDSHAREUSDT', 'GRAMPUSUSDT', 'LBCUSDT', 'STORJUSDT', 'MEMEAIUSDT', 'MSQUSDT', 'FHEUSDT', 'LSDCOINUSDT', 'MMUIUSDT', 'FNFSUSDT', 'CFNUSDT', 'SFUNDUSDT', '3ULLUSDT', 'VARAUSDT', 'POPCATUSDT', 'EXVGUSDT', 'MSBUSDT', 'GORTUSDT', 'HUSLUSDT', 'BSXUSDT', 'MEUSDT', 'TAPSUSDT', 'XFIUSDT', 'LAOSUSDT', 'TESUSDT', 'TBULLUSDT', 'LAIRUSDT', 'CLASHUBUSDT', 'MCONTENTUSDT', 'AUTOSUSDT', 'ANCUSDT', 'ZEREBROUSDT', 'GORAUSDT', 'OPULUSDT', 'POCHITAUSDT', 'APUUSDT', 'PGPTUSDT', 'CTKUSDT', 'CTPUSDT', 'ACTUSDT', 'GOHOMEUSDT', 'HOUSEUSDT', 'JELLYJELLYUSDT', 'WOLFSUSDT', 'UFDUSDT', 'SFLUSDT', 'TRUMP2024USDT', 'AGIXTUSDT', 'TRISIGUSDT', 'ARMYUSDT', 'MOCAUSDT', 'BULLSUSDT', 'HTXUSDT', 'WIZZUSDT', 'KFIUSDT', 'XAIUSDT', 'KZENUSDT', 'KISHUUSDT', 'LINAUSDT', 'MIRAUSDT', 'SOPHIAUSDT', 'JSMUSDT', 'PERPUSDT', 'DOGEXUSDT', 'LIBSUSDT', 'PASGUSDT', 'AIUSDT', 'PEANUTUSDT', 'VETUSDT', 'SWINGUSDT', 'RDEXUSDT', 'OCTUSDT', 'COMBOUSDT', 'WECOUSDT', 'PYTHONUSDT', 'PSTAKEUSDT', 'WUSDUSDT', 'SLFUSDT', 'EGCUSDT', 'KUJIUSDT', 'KATSUSDT', 'CAMUSDT', 'TERMINUSUSDT', 'GHXUSDT', 'GMMTUSDT', 'SACUSDT', 'LIQUIDIUMUSDT', 'USDPUSDT', 'PDA1USDT', 'DNOWUSDT', 'VIRTUALUSDT', 'MTSUSDT', 'WMTXUSDT', 'AZEROUSDT', 'VEXUSDT', 'EPILEPTICUSDT', 'GALAUSDT', 'BALLZUSDT', 'CRHUSDT', 'IONXUSDT', 'DATUSDT', 'STUFFUSDT', 'RACAUSDT', 'DREAMSUSDT', 'CRUSDT', 'MEFAUSDT', 'MTVUSDT', 'FCT2USDT', 'MNTCUSDT', 'KINUSDT', 'PROPCUSDT', 'SVPNUSDT', 'KEKIUSUSDT', 'MGTUSDT', 'MOTHERUSDT', 'ETHUSDT', 'CXTUSDT', 'AI16ZUSDT', 'ZEPHUSDT', 'MISTUSDT', 'KAONUSDT', 'HOMERUSDT', 'NPTUSDT', 'SSVUSDT', 'FUNUSDT', 'ZERCUSDT', 'MOLIUSDT', 'AGIUSDT', 'QUACKUSDT', 'WNZUSDT', 'SOULUSDT', 'WAXLUSDT', 'BLADEUSDT', 'TEMAUSDT', 'OORTUSDT', 'LUFCUSDT', 'XHPUSDT', 'MANASOLUSDT', 'BENQIUSDT', 'RENUSDT', 'CAMTUSDT', 'MMOSHUSDT', 'MERGEUSDT', 'LVLYUSDT', 'ASTUSDT', 'BARSIKUSDT', 'HEGEUSDT', 'SHROOMYUSDT', 'TUPUSDT', 'BFTUSDT', 'COOKUSDT', 'CATHEONUSDT', 'U2UUSDT', 'SOLXUSDT', 'WUSDT', 'TADAUSDT', 'RABIUSDT', 'TNTUSDT', 'ALTLAYERUSDT', 'XODEXUSDT', 'SMTUSDT', 'SOILUSDT', 'HOLDUSDT', 'STONKSUSDT', 'KASUSDT', 'MCRTUSDT', 'ZENQUSDT', 'DUSKUSDT', 'DESCIUSDT', 'PUFFERUSDT', 'VITEUSDT', 'GECKOAVAXUSDT', 'PEPECOINUSDT', 'CROSUSDT', 'PATEXUSDT', 'MEMESUSDT', 'CTAUSDT', 'MICHIUSDT', 'KDGUSDT', 'PONDUSDT', 'WSIUSDT', 'LUMIUSDT', 'HQUSDT', 'MAGATRUMPUSDT', 'STITCHUSDT', 'WOJAKUSDT', 'ETHFIUSDT', 'METAHEROUSDT', 'JASMYUSDT', 'NXRAUSDT', 'MEAIUSDT', 'DDMTUSDT', 'BBLUSDT', 'AREAUSDT', 'IGTUSDT', 'AKITAUSDT', 'OMIUSDT', 'AEUSDT', 'STARLUSDT', 'REALUSDT', 'SYNTUSDT', 'KILOUSDT', 'WSGUSDT', 'GINIUSDT', 'FOGUSDT', 'GPTWUSDT', 'HARDUSDT', 'MDIUSDT', 'STRDYUSDT', 'SEIYANUSDT', 'OKTUSDT', 'FRTSUSDT', 'CATGOLDUSDT', 'DTUSDT', 'WALUSDT', 'DEGOUSDT', 'ODOSUSDT', 'PORTOUSDT', 'MENGOUSDT', 'MTRGUSDT', 'WAFFLESUSDT', 'POKEMONUSDT', 'VELARUSDT', 'BLOCKWORLDUSDT', 'SLCUSDT', 'JEWELUSDT', 'GOLCUSDT', 'SLTUSDT', 'SUPUSDT', 'PDAUSDT', 'BTCMTUSDT', 'BONKUSDT', 'HUNDUSDT', 'KILTUSDT', 'AIBRAINUSDT', 'FLOWUSDT', 'NUBUSDT', 'CWSUSDT', 'CLGOUSDT', 'TTTUSDT', 'RIZUSDT', 'HATUSDT', 'LANDUSDT', 'BSVUSDT', 'WWYUSDT', 'SXCHUSDT', 'AI2USDT', 'ANLOGUSDT', 'QUAIUSDT', 'GORILLAUSDT', 'GFIUSDT', 'RFRMUSDT', 'PEPECATUSDT', 'PITUSDT', 'PIXELUSDT', 'XRPHUSDT', 'BLUEUSDT', 'MSNUSDT', 'UROUSDT', 'SUTUSDT', 'BLUBUSDT', 'DEGENUSDT', 'CPOOLUSDT', 'RDNTUSDT', 'SERSHUSDT', 'ARKUSDT', 'RFCUSDT', 'PLMCUSDT', 'XONEUSDT', 'BABYDOGEUSDT', 'BUMUSDT', 'IAGOUSDT', 'EPAYUSDT', 'NAVUSDT', 'OXTUSDT', 'WPAYUSDT', 'SPICEUSDT', 'DLCUSDT', 'FRBKUSDT', 'NMRUSDT', 'HAMBURGLARUSDT', 'ETHFUSDT', 'RFLUSDT', 'TRUMPEPEUSDT', 'ASTRAUSDT', 'USAUSDT', 'PRCLUSDT', 'PUSHUSDT', 'CDTUSDT', 'RPLSUSDT', 'XRPCUSDT', 'CGPTUSDT', 'YBRUSDT', 'ARCSOLUSDT', 'FANDUSDT', 'HGGUSDT', 'SLIMUSDT', 'KNINEUSDT', 'SCARCITYUSDT', 'VRUSDT', 'ITHACAUSDT', 'CLSUSDT', 'PRTGUSDT', 'NYANUSDT', 'KROUSDT', 'ASTROSUSDT', 'SNXUSDT', 'COTIUSDT', 'XDAGUSDT', 'MIUUSDT', 'ZKFUSDT', 'MOONUSDT', 'SKYAIUSDT', 'SATOXUSDT', 'NIMUSDT', 'JOLTUSDT', 'GXUSDT', 'OZKUSDT', 'UDSUSDT', 'BBUSDT', 'TNSRUSDT', 'EDGEUSDT', 'OMNOMUSDT', 'TALENTUSDT', 'APFCUSDT', 'PLBUSDT', 'ITUSDT', 'GNOUSDT', 'BDCAUSDT', 'HOPPYUSDT', 'SEXUSDT', 'BNRYUSDT', 'SKIUSDT', 'HARAMBEUSDT', 'RBXUSDT', 'KARRATUSDT', 'FORM1USDT', 'SHIBUSDT', 'EMTUSDT', 'SENATEUSDT', 'OMAXUSDT', 'TITSUSDT', 'LEGENDUSDT', 'ORAIXUSDT', 'SOONXUSDT', 'COMPUSDT', 'ONGUSDT', 'LLMUSDT', 'ZETRIXUSDT', 'LMWRUSDT', 'STGUSDT', 'RENDERUSDT', 'COLLATUSDT', 'RAINCOINUSDT', 'SHIFUUSDT', 'PSPSUSDT', 'HSTUSDT', 'VAIXUSDT', 'API3USDT', 'QUBEUSDT', 'SPACEUSDT', 'CLOUDUSDT', 'OKBUSDT', 'SHARKCATUSDT', 'RATSUSDT', 'PERRYUSDT', 'SIRIUSUSDT', 'INDEXUSDT', 'BISTUSDT', 'VENOMUSDT', 'DEBUSDT', 'BLSUSDT', 'ASMUSDT', 'BRLUSDT', 'RINGUSDT', 'AASTUSDT', 'HNTUSDT', 'ELDAUSDT', 'POKTUSDT', 'AXSUSDT', 'HAPIUSDT', 'ODINUSDT', 'DCDUSDT', 'MAZZEUSDT', 'SDTUSDT', 'KASPYUSDT', 'BLPUSDT', 'BLOCKASSETUSDT', 'PLOTSUSDT', 'ABUSDT', 'INITUSDT', 'XEPUSDT', 'JOCUSDT', 'MEXUSDT', 'OSHIUSDT', 'MEEUSDT', 'MAGAUSDT', 'SPXUSDT', 'DSLAUSDT', 'MVXUSDT', 'ONDOAIUSDT', 'BIDUSDT', 'TYTUSDT', 'MASAUSDT', 'PONGOUSDT', 'QGOVUSDT', 'BIZAUSDT', 'LOGXUSDT', 'ASVUSDT', 'XUSDUSDT', 'MOBILEUSDT', 'LIMEUSDT', 'FOXSYUSDT', 'DEEPSEEKUSDT', 'ANDYETHUSDT', 'TARAUSDT', 'GROWAIUSDT', 'MEYUSDT', 'AYINUSDT', 'STRXUSDT', 'MTRUSDT', 'GAUUSDT', 'MAGAETHUSDT', 'FETUSDT', 'SPECUSDT', 'PENGUUSDT', 'YNEUSDT', 'DOGE20USDT', 'UFOUSDT', 'WQTUSDT', 'UNIBOTUSDT', 'DAIUSDT', 'HAMUSDT', 'MOVRUSDT', 'FLXUSDT', 'XOXOUSDT', 'CLAYUSDT', 'RFDUSDT', 'BADGERUSDT', 'NEURUSDT', 'WITUSDT', 'SYNCUSDT', 'PROMPTUSDT', 'AITUSDT', 'RSTUSDT', 'BBFUSDT', 'PROUSDT', 'IMXUSDT', 'AIVAUSDT', 'GIKOUSDT', 'DTECUSDT', 'MYRIAUSDT', 'NSTUSDT', 'HGPTUSDT', 'KCSUSDT', 'SHIB2USDT', 'AWAREUSDT', 'KARUSDT', 'TRCLUSDT', 'HOOKUSDT', 'GHOADUSDT', 'TOKEUSDT', 'SARAUSDT', 'TELEMONUSDT', 'NDCUSDT', 'ACAUSDT', 'ARKMUSDT', 'DYORUSDT', 'PBXUSDT', 'ELUSDT', 'SPOTUSDT', 'PEANUTOGUSDT', 'ACEUSDT', 'NAVIXUSDT', 'EDGUSDT', 'WAXPUSDT', 'AXUSDT', 'CEBUSDT', 'CRUUSDT', 'AGNTUSDT', 'XDBUSDT', 'CORNUSDT', 'KAFUSDT', 'KOKOUSDT', 'BULLYUSDT', 'BXBTUSDT', 'BUCKUSDT', 'LOOPUSDT', 'VEILUSDT', 'SLAPUSDT', 'TRUUSDT', 'PLUGUSDT', 'PIBUSDT', 'BTSUSDT', 'FILUSDT', 'HIGHUSDT', 'ZFUSDT', 'MUBARAKUSDT', 'GPUUSDT', 'CKBUSDT', 'UNIUSDT', 'GXEUSDT', 'COPAUSDT', 'EXDUSDT', 'SHIBOOUSDT', 'BOMEUSDT', 'TRUMP1USDT', 'YACHTUSDT', 'HDNUSDT', 'ROSXUSDT', 'A47USDT', 'DECENTRALIZEDUSDT', 'MYROUSDT', 'DRFUSDT', 'BTCUSDT', 'WASUSDT', 'CLUSTRUSDT', 'BEFIUSDT', 'FREDUSDT', 'ALLINUSDT', 'INTOSUSDT', 'ZECUSDT', 'ASTRAAIUSDT', 'UBUUSDT', 'FACTRUSDT', 'SENDUSDT', 'WELFUSDT', 'ZEUSUSDT', 'AUCTIONUSDT', 'CELLUSDT', 'TIAUSDT', 'USDEUSDT', 'INDYUSDT', 'TALKUSDT', 'WBTUSDT', 'PXTUSDT', 'DRXUSDT', 'STONKSTOKENUSDT', 'MVRSUSDT', 'XAVAUSDT', 'WRKXUSDT', 'TAIUSDT', 'HOLUSDT', 'DUCKUSDT', 'STRDUSDT', 'DMAILUSDT', 'SAMOUSDT', 'MANCUSDT', 'MIDLEUSDT', 'SWCHUSDT', 'HVLOUSDT', 'WAGMIGAMESUSDT', 'DETFUSDT', 'RIFSOLUSDT', 'GUSDT', 'BSCPADUSDT', 'COQUSDT', 'CTXCUSDT', 'HRSEUSDT', 'PHOTOUSDT', 'PZPUSDT', 'INSUSDT', 'RIOUSDT', 'CATDOGUSDT', 'TPTUSDT', 'TUSDUSDT', 'DENTXUSDT', 'VONUSDT', 'OPTIMUSUSDT', 'KOLZUSDT', 'KOIUSDT', 'GATUSDT', 'PAXGUSDT', 'SITYUSDT', 'ZENIXUSDT', 'AMIUSDT', 'MATHUSDT', 'AGRSUSDT', 'FWCUSDT', 'BCXUSDT', 'DAOXUSDT', 'SHIRYOUSDT', 'EVRYUSDT', 'GCBUSDT', 'KNCUSDT', 'DVIUSDT', 'STRUMPUSDT', 'MLUSDT', 'XAI2USDT', 'EARNMUSDT', 'NEOUSDT', 'DEEPUSDT', 'MTMSUSDT', 'VANAUSDT', 'NEIROETHUSDT', 'RETSUSDT', 'BATTERYUSDT', 'EGLDUSDT', 'LWOLFUSDT', 'CLOREUSDT', 'WINUSDT', 'TAVAUSDT', 'MEGALANDUSDT', 'AGONUSDT', 'WQUILUSDT', 'LTCUSDT', 'MUSICUSDT', 'BABYTIGERUSDT', 'CGPUUSDT', 'AICEUSDT', 'EQBUSDT', 'IOTAUSDT', 'XIUSDT', 'SOUTHUSDT', 'HOLDVIPUSDT', 'LRCUSDT', 'MBOXUSDT', 'ETERNALUSDT', 'MAGASOLUSDT', 'BLUEMOVEUSDT', 'MCGUSDT', 'DMTRUSDT', 'SFMUSDT', 'CNGUSDT', 'PACKUSDT', 'OASUSDT', 'SKORAIUSDT', 'AQAUSDT', 'KAYENUSDT', 'TORNUSDT', 'ENJUSDT', 'RWNUSDT', 'LRDSUSDT', 'FLTUSDT', 'AURORAUSDT', 'LUNAUSDT', 'BOTTOUSDT', 'NEOXUSDT', 'RADARUSDT', 'FLDTUSDT', 'TIMUSDT']  # أضف أزواجك هنا مثل ['BTCUSDT', 'ETHUSDT']

# روابط المنصات اللامركزية
DEX_SWAP_LINKS = {
    "bsc": "https://pancakeswap.finance/swap?outputCurrency={contract}",
    "ethereum": "https://app.uniswap.org/#/swap?outputCurrency={contract}",
    "solana": "https://raydium.io/swap/?inputCurrency=USDC&outputCurrency={contract}",
    "arbitrum": "https://app.uniswap.org/#/swap?chain=arbitrum&outputCurrency={contract}",
    "polygon": "https://quickswap.exchange/#/swap?outputCurrency={contract}",
    "avalanche": "https://traderjoexyz.com/avalanche/trade?outputCurrency={contract}",
    "optimism": "https://app.uniswap.org/#/swap?chain=optimism&outputCurrency={contract}",
    "fantom": "https://spookyswap.finance/swap?outputCurrency={contract}",
}

# إعدادات السيولة
MIN_LIQUIDITY = 300  # الحد الأدنى للسيولة بالدولار
MAX_SLIPPAGE = 5  # الحد الأقصى المسموح به للانزلاق السعري (%)
MAX_WITHDRAWAL_FEE_PERCENT = 5  # الحد الأقصى لرسوم السحب (% من الصفقة)
TRADE_VOLUME = 20  # حجم الصفقة المستهدف بالدولار

def create_signature(query_string, secret_key):
    return hmac.new(secret_key.encode(), query_string.encode(), hashlib.sha256).hexdigest()

def get_contract_addresses():
    timestamp = str(int(time.time() * 1000))
    query_string = f"timestamp={timestamp}"
    signature = create_signature(query_string, SECRET_KEY)
    headers = {"X-MEXC-APIKEY": API_KEY}
    url = f"{MEXC_API_URL}/capital/config/getall?{query_string}&signature={signature}"

    response = requests.get(url, headers=headers)

    valid_networks = {
        "Solana(SOL)": "solana",
        "BNB Smart Chain(BEP20)": "bsc",
        "Ethereum(ERC20)": "ethereum",
        "Polygon(MATIC)": "polygon",
        "Avalanche C-Chain": "avalanche",
        "Arbitrum One": "arbitrum",
        "Optimism": "optimism",
        "Fantom": "fantom",
    }

    if response.status_code == 200:
        data = response.json()
        contract_list = []
        for token in data:
            coin = token.get("coin")
            for network in token.get("networkList", []):
                contract = network.get("contract")
                network_name = network.get("network")
                if network_name in valid_networks:
                    withdraw_fee = network.get("withdrawFee", 0)
                    withdraw_min = network.get("withdrawMin", "N/A")
                    withdraw_max = network.get("withdrawMax", "N/A")
                    deposit_enable = network.get("depositEnable", False)
                    withdraw_enable = network.get("withdrawEnable", False)

                    contract_list.append({
                        "symbol": coin,
                        "contract_address": contract,
                        "network": valid_networks[network_name],
                        "withdraw_fee": withdraw_fee,
                        "withdraw_min": withdraw_min,
                        "withdraw_max": withdraw_max,
                        "deposit_enable": deposit_enable,
                        "withdraw_enable": withdraw_enable
                    })
        return contract_list
    else:
        print(f"❌ Error getting contracts: {response.status_code} - {response.text}")
        return []

def get_dexscreener_price(chain_id, contract_address):
    try:
        url = f"{DEX_API_URL}/token-pairs/v1/{chain_id}/{contract_address}"
        response = requests.get(url, timeout=30)
        response.raise_for_status()

        data = response.json()
        if isinstance(data, list):
            pairs = data
        elif isinstance(data, dict) and 'pairs' in data:
            pairs = data['pairs']
        else:
            print(f"⚠️ Unexpected DexScreener response format for {chain_id}/{contract_address}")
            return None, None

        best_pair = None
        highest_liquidity = 0

        for pair in pairs:
            liquidity = pair.get('liquidity', {}).get('usd', 0)
            if liquidity > highest_liquidity:
                highest_liquidity = liquidity
                best_pair = pair

        if best_pair:
            price_usd = best_pair.get('priceUsd')
            if price_usd:
                print(f"ℹ️ DEX Price for {contract_address}: ${float(price_usd):.8f} (Liquidity: ${highest_liquidity:.2f})")
                return float(price_usd), highest_liquidity
        print(f"⚠️ No valid price found for {contract_address} on {chain_id}")
        return None, None
    except requests.exceptions.RequestException as e:
        print(f"❌ DexScreener request error for {chain_id}/{contract_address}: {str(e)}")
        return None, None

def get_order_book(symbol):
    symbol += "USDT"
    url = f"{MEXC_API_URL}/depth"
    params = {'symbol': symbol, 'limit': 40}
    try:
        response = requests.get(url, params=params)
        if response.status_code == 200:
            return response.json()
        else:
            print(f"❌ MEXC order book error for {symbol}: {response.status_code} - {response.text}")
            return None
    except requests.exceptions.RequestException as e:
        print(f"❌ MEXC order book request error for {symbol}: {str(e)}")
        return None

def get_mexc_price(symbol):
    url = f"{MEXC_API_URL}/ticker/price?symbol={symbol}USDT"
    try:
        response = requests.get(url).json()
        if 'price' in response:
            price = float(response['price'])
            print(f"ℹ️ MEXC Price for {symbol}: ${price:.8f}")
            return price
        print(f"⚠️ MEXC price not found for {symbol}")
        return None
    except requests.exceptions.RequestException as e:
        print(f"❌ MEXC price request error for {symbol}: {str(e)}")
        return None

def get_mexc_sell_price(symbol, target_amount=TRADE_VOLUME):
    order_book = get_order_book(symbol)
    if not order_book:
        print(f"⚠️ No order book data for {symbol} (sell price)")
        return None

    total_price = 0
    total_quantity = 0
    total_value = 0

    for ask in order_book['asks']:
        price = float(ask[0])
        quantity = float(ask[1])
        value = price * quantity

        if total_value < target_amount:
            total_price += price * quantity
            total_quantity += quantity
            total_value += value

        if total_value >= target_amount:
            break

    if total_quantity == 0:
        print(f"⚠️ No asks in order book for {symbol}")
        return None

    average_price = total_price / total_quantity
    print(f"ℹ️ MEXC Sell Price for {symbol} (${target_amount} volume): ${average_price:.8f}")
    return round(average_price, 8)

def get_mexc_buy_price(symbol, target_amount=TRADE_VOLUME):
    order_book = get_order_book(symbol)
    if not order_book:
        print(f"⚠️ No order book data for {symbol} (buy price)")
        return None

    total_price = 0
    total_quantity = 0
    total_value = 0

    for bid in order_book['bids']:
        price = float(bid[0])
        quantity = float(bid[1])
        value = price * quantity

        if total_value < target_amount:
            total_price += price * quantity
            total_quantity += quantity
            total_value += value

        if total_value >= target_amount:
            break

    if total_quantity == 0:
        print(f"⚠️ No bids in order book for {symbol}")
        return None

    average_price = total_price / total_quantity
    print(f"ℹ️ MEXC Buy Price for {symbol} (${target_amount} volume): ${average_price:.8f}")
    return round(average_price, 8)

async def check_price_difference(context: CallbackContext):
    contracts = get_contract_addresses()
    if not contracts:
        print("❌ No contracts data available")
        return

    print("\n" + "="*50)
    print(f"✅ Starting spread check for {len(TARGET_PAIRS)} target pairs at {time.strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*50 + "\n")

    for contract in contracts:
        symbol = contract["symbol"]
        if f"{symbol}USDT" not in TARGET_PAIRS:
            continue

        print("\n" + "-"*40)
        print(f"🔍 Scanning pair: {symbol}")
        print("-"*40)

        contract_address = contract["contract_address"]
        network = contract["network"]

        try:
            withdraw_fee = float(contract["withdraw_fee"]) if contract["withdraw_fee"] != "N/A" else 0.0
        except ValueError:
            withdraw_fee = 0.0
            print(f"⚠️ Could not parse withdraw fee for {symbol}, using 0")

        with open("ignore.txt", "r", encoding="utf-8") as file:
            ignore_list = file.read().splitlines()

        if symbol in ignore_list:
            print(f"⏩ {symbol} is in ignore list, skipping...")
            continue

        print(f"ℹ️ Network: {network}, Contract: {contract_address}")
        print(f"ℹ️ Withdraw Fee: {withdraw_fee} {symbol}")
        print(f"ℹ️ Deposit Enabled: {'✅' if contract['deposit_enable'] else '❌'}")
        print(f"ℹ️ Withdraw Enabled: {'✅' if contract['withdraw_enable'] else '❌'}")

        mexc_price_buy = get_mexc_buy_price(symbol)
        mexc_price_sell = get_mexc_sell_price(symbol)

        if mexc_price_buy is None or mexc_price_sell is None:
            print(f"⚠️ Could not get MEXC order book prices for {symbol}, skipping...")
            continue

        mexc_price = get_mexc_price(symbol)
        if mexc_price is None:
            print(f"⚠️ Could not get MEXC ticker price for {symbol}, skipping...")
            continue

        dex_price, liquidity = get_dexscreener_price(network, contract_address)
        if dex_price is None or liquidity is None:
            print(f"⚠️ Could not get DEX price for {symbol}, skipping...")
            continue

        # التحقق من شروط السيولة
        if liquidity < MIN_LIQUIDITY:
            print(f"⚠️ Low liquidity (${liquidity:.2f}) for {symbol}, skipping...")
            continue

        # حساب رسوم السحب كنسبة مئوية من الصفقة
        withdrawal_fee_percent = (withdraw_fee * dex_price / TRADE_VOLUME) * 100
        if withdrawal_fee_percent > MAX_WITHDRAWAL_FEE_PERCENT:
            print(f"⚠️ High withdrawal fee ({withdrawal_fee_percent:.2f}%) for {symbol}, skipping...")
            continue

        spread_without_fee = ((mexc_price - dex_price) / dex_price) * 100
        print(f"ℹ️ Price Difference: {spread_without_fee:.2f}%")
        print(f"ℹ️ Liquidity: ${liquidity:.2f}")
        print(f"ℹ️ Withdrawal Fee: {withdraw_fee} {symbol} ({withdrawal_fee_percent:.2f}% of trade)")

        if abs(spread_without_fee) <= 5 or abs(spread_without_fee) > 300:
            print(f"ℹ️ Price difference {spread_without_fee:.2f}% is outside target range (5%-300%), skipping...")
            continue

        mexc_link = f"https://www.mexc.com/ru-RU/exchange/{symbol}_USDT"
        dex_link = f"https://dexscreener.com/{network}/{contract_address}"
        dex_swap_link = DEX_SWAP_LINKS.get(network, "").format(contract=contract_address)
        difference = ((mexc_price - dex_price) / dex_price) * 100
        difference_buy = ((mexc_price_buy - dex_price) / dex_price) * 100
        difference_sell = ((mexc_price_sell - dex_price) / dex_price) * 100

        print(f"ℹ️ Detailed Price Analysis:")
        print(f"  - MEXC Ticker Price: ${mexc_price:.8f}")
        print(f"  - DEX Price: ${dex_price:.8f}")
        print(f"  - MEXC Buy Price (${TRADE_VOLUME} volume): ${mexc_price_buy:.8f} ({difference_buy:.2f}% difference)")
        print(f"  - MEXC Sell Price (${TRADE_VOLUME} volume): ${mexc_price_sell:.8f} ({difference_sell:.2f}% difference)")
        print(f"  - Liquidity: ${liquidity:.2f}")
        print(f"  - Withdrawal Fee: {withdraw_fee} {symbol} ({withdrawal_fee_percent:.2f}% of trade)")

        global show_massage
        if show_massage:
            if abs(difference) > 799:
                print(f"⚠️ Price difference {difference:.2f}% is too high (>800%), skipping...")
                continue
            elif difference_buy >= 10:
                if mexc_price > dex_price:
                    if contract["deposit_enable"]:
                        message = (
                            f"📈 **Network**: {network}\n"
                            f"🔄 **Opportunity**: Buy on DEX → Sell on MEXC\n\n"
                            f"🔹 **Coin**: {symbol}\n"
                            f"💵 **MEXC Price**: ${mexc_price:.8f} | [MEXC Link]({mexc_link})\n"
                            f"📉 **DEX Price**: ${dex_price:.8f} | [DexScreener]({dex_link})\n"
                            f"💰 **Liquidity**: ${liquidity:.2f}\n"
                            f"🔗 **Swap on DEX**: [Buy {symbol} here]({dex_swap_link})\n"
                            f"📊 **Difference**: +{difference_buy:.2f}%\n"
                            f"💸 **Withdrawal Fee**: {withdraw_fee} {symbol} ({withdrawal_fee_percent:.2f}%)\n"
                            f"🔑 **Deposit enabled**: {'✅' if contract['deposit_enable'] else '❌'}"
                        )
                        print(f"🚀 Found profitable opportunity (Buy on DEX): {difference_buy:.2f}%")
                        await context.bot.send_message(chat_id=ADMIN_ID, text=message, parse_mode='Markdown')
                    else:
                        print(f"ℹ️ Deposit disabled for {symbol}, can't execute buy on DEX strategy")
                else:
                    print(f"ℹ️ MEXC price not higher than DEX for {symbol}, no opportunity")

            elif difference_sell <= -10:
                if contract["withdraw_enable"]:
                    message = (
                        f"📈 **Network**: {network}\n"
                        f"🔄 **Opportunity**: Buy on MEXC → Sell on DEX\n\n"
                        f"🔹 **Coin**: {symbol}\n"
                        f"💵 **MEXC Price**: ${mexc_price:.8f} | [MEXC Link]({mexc_link})\n"
                        f"📉 **DEX Price**: ${dex_price:.8f} | [DexScreener]({dex_link})\n"
                        f"💰 **Liquidity**: ${liquidity:.2f}\n"
                        f"🔗 **Swap on DEX**: [Sell {symbol} here]({dex_swap_link})\n"
                        f"📊 **Difference**: {difference_sell:.2f}%\n"
                        f"💸 **Withdrawal Fee**: {withdraw_fee} {symbol} ({withdrawal_fee_percent:.2f}%)\n"
                        f"🔑 **Withdrawal enabled**: {'✅' if contract['withdraw_enable'] else '❌'}"
                    )
                    print(f"🚀 Found profitable opportunity (Buy on MEXC): {difference_sell:.2f}%")
                    await context.bot.send_message(chat_id=ADMIN_ID, text=message, parse_mode='Markdown')
                else:
                    print(f"ℹ️ Withdraw disabled for {symbol}, can't execute buy on MEXC strategy")
            else:
                print(f"ℹ️ No significant price difference found for {symbol} (Buy: {difference_buy:.2f}%, Sell: {difference_sell:.2f}%)")

async def start_checking_job(context: CallbackContext):
    global is_checking_active
    is_checking_active = True
    while is_checking_active:
        await check_price_difference(context)
        await asyncio.sleep(60)

async def stop_checking_job():
    global is_checking_active
    is_checking_active = False

async def start(update: Update, context: CallbackContext):
    await update.message.reply_text('✅ Bot is running automatically with 10% spread threshold.')

async def button(update: Update, context: CallbackContext):
    query = update.callback_query
    await query.answer()

    global show_massage

    if query.data == 'start_checking':
        if update.effective_user.id == ADMIN_ID:
            if not is_checking_active:
                await query.edit_message_text(text="✅ Spread checker started!")
                show_massage = True
                context.job_queue.run_repeating(
                    check_price_difference,
                    interval=60.0,
                    first=0.0,
                    chat_id=ADMIN_ID
                )
            else:
                await query.edit_message_text(text="❌ Checking is already active.")
        else:
            await query.edit_message_text(text="❌ You don't have permission to start checking.")

    elif query.data == 'stop_showing':
        if update.effective_user.id == ADMIN_ID:
            if is_checking_active:
                await stop_checking_job()
                show_massage = False
                await query.edit_message_text(text="⛔ Stopped showing messages.")
            else:
                await query.edit_message_text(text="❌ Checking wasn't started.")
        else:
            await query.edit_message_text(text="❌ You don't have permission to stop checking.")

async def info(update: Update, context: CallbackContext):
    await update.message.reply_text("Add to ignore: /add_ignore [symbol]")

async def add_ignore(update: Update, context: CallbackContext):
    if update.effective_user.id != ADMIN_ID:
        await update.message.reply_text("❌ You don't have permission.")
        return

    try:
        symbol = context.args[0].upper()
    except IndexError:
        await update.message.reply_text("Error: Please provide a coin symbol.")
        return

    with open("ignore.txt", "r", encoding="utf-8") as file:
        ignore_list = file.read().splitlines()

    if symbol in ignore_list:
        await update.message.reply_text(f"Symbol '{symbol}' already exists.")
    else:
        with open("ignore.txt", "a", encoding="utf-8") as file:
            file.write(symbol + "\n")

        await update.message.reply_text(f"Symbol '{symbol}' added to ignore list.")

def main():
    application = Application.builder().token("7887167602:AAEmpIny8aLfno4D-LbmEaP4hAjENKDdaoA").build()

    # بدء الفحص تلقائيًا عند التشغيل
    application.job_queue.run_repeating(
        check_price_difference,
        interval=60.0,
        first=0.0,
        chat_id=ADMIN_ID
    )

    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("info", info))
    application.add_handler(CommandHandler("add_ignore", add_ignore))
    application.add_handler(CallbackQueryHandler(button))

    application.run_polling()

if __name__ == "__main__":
    main()